# Generated by Django 6.1.1 on 2026-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuelstation_lat_lon_idx'), models.Index(fields=['state', 'city'], name='fuelstation_state_city_idx')],
            },
        ),
    ]
